

```{r}
library(tidyverse)
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")
options(mc.cores = parallel::detectCores())
library(haven)
library(posterior)
library(dbarts)
library(parallel)
library(nonlinvarsel)
source("R/varselaux.r")
```

```{r}
dt <- readRDS("data/Senegal/dtwp.rds")
dt <- dt %>% filter(qnorm(.1) < e & e < qnorm(.9))
```

#load the  probabilities
```{r}
source("R/princeB.r")
prob <- readRDS("data/Senegal/princeB_prob_thin.rds")

p_n <- prob[, , "p_n", ]
p_a <- prob[, , "p_a", ]
p_c <- 1 - p_n - p_a

my1c <- prob[, , "m_y1c", ]
my0c <- prob[, , "m_y0c", ]
cate <- my1c - my0c
```



*===================*
*** find segments ***
*===================*
```{r}
selvar <- readRDS("data/Senegal/selvar_tau.rds")
library(rpart)
library(partykit)
library(rpart.plot)

colnames(dt)
dt$cate <- apply(cate, 3, mean)
dt$w <- apply(p_c, 3, mean)
set.seed(0203)
rp_tau <- rpart(cate ~ . - w
  , select(dt, cate, any_of(selvar), w)
  , control = rpart.control(cp = 0, maxdepth = 3L)
  , weights = w
)
#rp_tau <- prune(rp_tau, cp = .01)
rpart.plot:::rpart.plot(rp_tau)


png("output/Senegal/rtree_tau.png", width = 480 * 6, heigh = 480 * 3, res = 300)
rpart.plot(rp_tau)
dev.off()

#segments
rules <- partykit:::.list.rules.party(as.party(rp_tau))
dt$segment <- NULL
dt$segment  <- factor(
  predict(as.party(rp_tau)
    , type = "node"
    , newdata = dt
  ), labels = rules
)
saveRDS(dt, "data/Senegal/dtwp_wseg.rds")
```




* get segment-specific estimates 
```{r}
library(gt)

fitted_tau <- \(include = NULL) {
  if (is.null(include)) {
    include <- rep(TRUE, nrow(dt))
  }
  p_c  <- p_c[, , include]
  my1c <- my1c[, , include]
  my0c <- my0c[, , include]
  delta <- my1c - my0c
  est <- apply(delta * p_c, 1:2, sum) / apply(p_c, 1:2, sum)
  m   <- mean(est)
  s   <- sd(est)
  ci9 <- quantile(as.vector(est), c(.05, .95))
  pgt0 <- mean(est > 0)
  data.frame(segment = "overall", m, s, ci9[1], ci9[2], pgt0)
}


sgm_tb  <- lapply(levels(dt$segment), \(s) {
  include <- dt$segment  == s
  res <- fitted_tau(include)
  res$segment <- s
  res
}) %>% bind_rows

all <- fitted_tau()
sgm_tb <- rbind(all, sgm_tb)

sgm_tb %>%
  gt %>%
  tab_header(
    title = "Effect of contraceptive use on employment by subpopulation"
  ) %>%
  fmt_number(columns = where(is.numeric), decimals = 3)  %>%
  cols_merge_range(m, s, sep = " (")  %>%
  cols_merge_range(ci9.1., ci9.2., sep = ", ")  %>%
  cols_label(ci9.1. = "90%CI") %>%
  gtsave("output/Senegal/hetero_eff.html")
```


Plot effect by segment
```{r}
sgm_tb$osegment <- sgm_tb$segment
sgm_tb$osegment
table(dt$education)

nice_names <- c(
  "overall"
  , "not sexually active, did not work last year, less than 20 years old"
  , "not sexually active, did not work last year, 20 years or more"
  , "not sexually active, work last year, at least some secondary education"
  , "not sexually active, work last year, primary education or less"
  , "sexually active, 30 or more years old, did not work last year"
  , "sexually active, 30 or more years old, work last year"
  , "sexually active, less than 30 years old, at least some secondary education"
  , "sexually active, less than 30 years old, primary education or less"
)

sgm_tb$segment <- nice_names
saveRDS(sgm_tb, "data/Senegal/sgm_tb.rds")
```

```{r}
hetero_plot <-
  sgm_tb %>%
  ggplot(aes(y = reorder(stringr::str_wrap(segment, 40), desc(m))
    , x = m, col = (segment != "overall")
  )) +
  geom_vline(xintercept = 0, col = "grey") +
  geom_errorbar(aes(xmin = ci9.1., xmax = ci9.2.), width = .5) +
  geom_point() +
  labs(title = ""
    , x = "Subgroup-specific effect size estimate (and 90% CI)"
    , y = ""
  ) +
  theme_minimal() +
  theme(legend.position = "none")
hetero_plot

ggsave("output/Senegal/hetero_plot.png", hetero_plot
  , width = 6, heigh = 5, bg = "white"
)
```

* test hetergoneity 
```{r}

g1 <- with(dt, segment == levels(segment)[which.min(tapply(cate, segment, mean))])
g2 <- with(dt, segment == levels(segment)[which.max(tapply(cate, segment, mean))])

est1 <- apply((my1c - my0c)[, , g1] * p_c[, , g1], 1:2, sum) /
  apply(p_c[, , g1], 1:2, sum)
est2 <- apply((my1c - my0c)[, , g2] * p_c[, , g2], 1:2, sum) /
  apply(p_c[, , g2], 1:2, sum)

summary(as.vector(est1))
summary(as.vector(est2))

d <- as.vector(est2 - est1)
saveRDS(d, "output/Senegal/d.rds")
summary(d)
hist(d)
mean(d > 0, na.rm = TRUE)


png("output/Senegal/hi_tau.png", width = 480 * 3.5, heigh = 480 * 3.5, res = 300)
my_breaks <- hist(d)$breaks
my_colors <- rep(adjustcolor("dark blue", alpha.f = 0.2), length(my_breaks))
my_colors[my_breaks >= 0] <- adjustcolor("gray", alpha.f = 0.5)
my_colors
hist(d, xlab = "Difference in effect across subgroups (d)"
  , main = ""
  , col = my_colors
)
abline(v = 0, col = "gray", lty = 2)
text(par("usr")[2] * .7, par("usr")[4] * .8
  , paste("mean(d) = ", round(mean(d, na.rm = TRUE), 2)
    , "\n", "pr(d > 0|data) = ", round(mean(d > 0, na.rm = TRUE), 2)
  )
)
dev.off()
```