```{r} 
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")

library(haven)
library(tidyverse)
library(parallel)
source("R/princeB.r")
```


get DHS data
```{r}
dhs <- readRDS("data/Nigeria/NG2018.rds")
dim(dhs)
colnames(dhs)
```


```{r}
sdt <- readRDS("data/Nigeria/dt2w.rds") %>% select(-c(Y:wt))
in_dhs <- colnames(sdt)[colnames(sdt) %in% colnames(dhs)]
colnames(sdt)[!colnames(sdt) %in% in_dhs]
colnames(dhs)[!colnames(dhs) %in% in_dhs]

colnames(dhs)
not_in_dhs <- c(
  "has_money", "selfeff_obtain"
  , "att_safety", "att_autonomous_use"
)
#dhs[, not_in_dhs] <- replicate(nrow(dhs), c(1, 1, 1, 0)) %>% t
```

(re) fit the propensity to be in the 4 intervention cities
to the source data and then compute in the DHS data
```{r}
set.seed(0203)
me <- bart2(Z ~ .
  , data = sdt[, !colnames(sdt) %in% not_in_dhs]
  , n.trees = 75L
  , k = 2
  , keepTrees = TRUE
)
sort(- apply(me$varcount, 3, mean))
invisible(me$fit$state)
saveRDS(me, "data/Nigeria/propensity_bart.rds")

dhs$e <- apply(predict(me, newdata = dhs, type = "bart"), 2, mean)
summary(dhs$e)
```



MULTIPLE IMPUTATION
```{r}
add_bernoulli_error <- \(p) {
  array(rbinom(prod(dim(p)), 1,  p),
    dim = dim(p)
  )
}
set.seed(0203)

mi <- lapply(not_in_dhs, \(v) {
  x <- select(sdt, -all_of(not_in_dhs), - Z)
  y <- sdt[[v]]
  mi <- bart2(x, y
    , dhs
    , n.trees = 75L, k = 2
    , n.chains = 20
  )
  mi$yhat.test |> pnorm() |> add_bernoulli_error()
})
mi <- abind::abind(mi, along = 4) |> aperm(c(3, 4, 2, 1))


dimnames(mi) <- list(
  respondent = NULL
  , var = not_in_dhs
  , draw = NULL
  , chain = NULL
)

saveRDS(mi, paste0("data/Nigeria/mi.rds"))
```


predict counterfactual oucomes for DHS respondents
Base on BART trees fit to source study 
```{r}
mi <- readRDS(paste0("data/Nigeria/mi.rds"))

py_list <- mclapply(1:20, \(chain) {
  stree <- readRDS(paste0("data/Nigeria/stree_", chain, ".rds"))
  sample <- unique(stree$sample)
  py <- lapply(seq_along(sample), \(s) {
    x <- dhs
    x[, not_in_dhs] <- NULL
    # inject draw-specific imputations
    x[, not_in_dhs] <- mi[, , s, chain]

    scaled_x <- x |>
      select(all_of(names(attr(stree, "scaled:center")))) |>
      scale(attr(stree, "scaled:center"), attr(stree, "scaled:scale"))

    y0 <- subset(stree, m == "y0co") |> predict_one_draw(scaled_x, sample[s])
    y1 <- subset(stree, m == "y1co") |> predict_one_draw(scaled_x, sample[s])
    cbind(y0, y1)
  })
  py_arr <- simplify2array(py)
}, mc.cores = 16
)

py_arr <- simplify2array(py_list)
py_arr <- array(py_arr, c(dim(py_arr)[1:2], prod(dim(py_arr)[3:4])))
dim(py_arr)

dhs$y0 <- py_arr[, 1, ]
dhs$y1 <- py_arr[, 2, ]
saveRDS(dhs, paste0("data/Nigeria/dhs_plus.rds"))
```