

```{r}
library(tidyverse)
options(digitis = 3)
options(scipen = 10^5)
options(help_type = "html")
library(tidyverse)
source("R/generalB.r")
source("R/princeB.r")
library(survey)
library(dbarts)
library(haven)
library(parallel)
```

Load data
```{r}
mi <- readRDS(paste0("data/Nigeria/mi.rds"))
si <- apply(mi, 1:2, mean)

dhs <- readRDS("data/Nigeria/dhs_plus.rds")
dhs <- cbind(dhs, si)
dhs <- dhs |>
  filter(anymodern_ever == 0 & anymodern_now == 0 & want_no_birth == 1)
```

```{r}
#2w lredy exclude e>.9 or e <.1
sdt <- readRDS("data/Nigeria/dt2w.rds")
in_dhs <- colnames(sdt)[colnames(sdt) %in% colnames(dhs)]

```

```{r}
sdt$urban <- sdt$in5states <- NA
common_cols <- intersect(colnames(dhs), colnames(sdt))

stacked_dt <-
  bind_rows(
    dhs %>% select(all_of(common_cols))
    , sdt %>% select(all_of(common_cols))
    , .id = "source"
  ) %>%
  mutate(source = as.numeric(source) - 1)

table(stacked_dt$source)
```


PROPENSITY TO BE IN SOURCE, P(T = 0|X, T = 1 or T = 0)
```{r}
colnames(stacked_dt)
set.seed(0203)
m_pi <- bart2(source ~ .
  , data = select(stacked_dt
    , - c(urban, wt, in5states
      , selfeff_obtain, att_safety, att_autonomous_use, has_money
    )
  )
)
sort(apply(m_pi$varcount, 3, mean), decreasing = TRUE)

pi_t <- fitted(m_pi)
boxplot(pi_t ~ stacked_dt$source)
tapply(pi_t, stacked_dt$source, mean)
tapply(pi_t, stacked_dt$source, sd)

stacked_dt %>%
  group_by(source) %>%
  reframe(across(everything(), mean)) %>% t %>% round(3)
```


compute complier propensity, P(C|X, T = 0)
(this is the probability of being a complier as a funciton of X
not the posterior pedictive probability of being a complier given observed Y as well which is saved in wt)
```{r}
pi_c <- lapply(1:4, \(i) {
  stree <- readRDS(paste0("data/Nigeria/stree_", i, ".rds"))

  scaled_x <- stacked_dt %>%
    select(all_of(names(attr(stree, "scaled:center")))) %>%
    scale(attr(stree, "scaled:center"), attr(stree, "scaled:scale"))

  eco <- predict(subset(stree, m == "co"), scaled_x, n_cores = 18)
  eco
})

stacked_dt$pi_c <- apply(pi_c %>% bind_cols, 1, mean)
tapply(stacked_dt$pi_c, stacked_dt$source, mean)
```

PLOT
```{r}
library(scales)
stacked_dt$pi_s <- with(stacked_dt, pi_c * pi_t)
tapply(stacked_dt$pi_s, stacked_dt$source, mean)
stacked_dt$e_s <- qlogis(stacked_dt$pi_s)

m <- with(filter(stacked_dt, source == 1), weighted.mean(e_s, wt))
m2 <- with(filter(stacked_dt, source == 1), weighted.mean((e_s)^2, wt))
s <- sqrt(m2 - m^2)
stacked_dt$e_s_tilde <- (stacked_dt$e_s - m) / s
saveRDS(stacked_dt, "data/Nigeria/stacked_dt.rds")
```
```{r}
oplot <- ggplot() +
  geom_density(
    data = data.frame(
      filter(stacked_dt, source == 0, urban == 1, in5states == 1)
      , pop = "2"
    )
    , aes(x = e_s_tilde, weight = wt, fill = pop)
    , alpha = .4, color = NA
  ) +
  geom_density(
    data = data.frame(filter(stacked_dt, source == 0, urban == 1), pop = "3")
    , aes(x = e_s_tilde, weight = wt, fill = pop)
    , alpha = .4, color = NA
  ) +
  geom_density(
    data = data.frame(filter(stacked_dt, source == 0), pop = "4")
    , aes(x = e_s_tilde, weight = wt, fill = pop)
    , alpha = .4, color = NA
  ) +
  geom_density(
    data = data.frame(filter(stacked_dt, source == 1), pop = "1")
    , aes(x = e_s_tilde, weight = wt, fill = pop)
    , alpha = .4, color = NA
  ) +
  #xlim(-25, 5) +
  xlab("standardized selection score") +
  ylab("density") +
  theme_minimal() +
  theme(legend.position = "inside", legend.position.inside = c(.3, .8)) +
  theme(legend.title = element_blank()) +
  scale_fill_manual(values = hue_pal()(4)
    , name = element_blank()
    , labels = c(
      "Compliers (source study)"
      , "Urban, same states (DHS)"
      , "Urban, all state (DHS)"
      , "Urban and rural, all states (DHS)"
    )
  )
oplot

png("output/Nigeria/overlap.png"
    , width = 480 * 3, heigh = 480 * 2.5, res = 300)
oplot
dev.off()
```





#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SENSITIVITY
```{r}
library(gt)
dhs$sp <-
  dhs$anymodern_ever == 0 &
  dhs$anymodern_now == 0 &
  dhs$want_no_birth == 1
table(dhs$sp)

q <- with(subset(stacked_dt, source == 1, c(e_s_tilde, wt))
  , Hmisc::wtd.quantile(e_s_tilde, wt, 5 / 100)
)
q %>% round(3)

e <- unlist(subset(stacked_dt, source == 0, e_s_tilde))
mean(e[dhs$sp == 1 & dhs$urban == 1] < q)

#gen_b(with(dhs, y1 - y0), dhs$sp == 1 & dhs$urban == 1)

dhs1 <- dhs
dhs1$d <- with(dhs, y1 - y0)
dhs1$d[e < q, ] <- 0
us <- gen_b(dhs1$d, dhs$sp == 1 & dhs$urban == 1 & dhs$in5states == 1)
ua <- gen_b(dhs1$d, dhs$sp == 1 & dhs$urban == 1)
ur <- gen_b(dhs1$d, dhs$sp == 1)

bind_rows(us, ua, ur) %>%
  mutate(names = c("us", "ua", "ur")) %>%
  gt %>%
  gtsave("output/Nigeria/sa_overlap.html")
```